// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass017 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass017)
const floorBaseGrass017transform = new Transform({
  position: new Vector3(24, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass017.addComponentOrReplace(floorBaseGrass017transform)
const floorBaseGrass017GLTFShape = new GLTFShape("models/grass/FloorBaseGrass_01.glb")
floorBaseGrass017GLTFShape.withCollisions = true
floorBaseGrass017GLTFShape.isPointerBlocker = true
floorBaseGrass017GLTFShape.visible = true
floorBaseGrass017.addComponentOrReplace(floorBaseGrass017GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0110 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0110)
const floorBaseGrass0110transform = new Transform({
  position: new Vector3(8, 0, 24),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0110.addComponentOrReplace(floorBaseGrass0110transform)
floorBaseGrass0110.addComponentOrReplace(floorBaseGrass017GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0111 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0111)
const floorBaseGrass0111transform = new Transform({
  position: new Vector3(24, 0, 24),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0111.addComponentOrReplace(floorBaseGrass0111transform)
floorBaseGrass0111.addComponentOrReplace(floorBaseGrass017GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0212 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0212)
const stoneSlabSmall0212transform = new Transform({
  position: new Vector3(19, 0, 0),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0212.addComponentOrReplace(stoneSlabSmall0212transform)
const stoneSlabSmall0212GLTFShape = new GLTFShape("models/stoneSlab/StoneSlabSmall_02/StoneSlabSmall_02.glb")
stoneSlabSmall0212GLTFShape.withCollisions = true
stoneSlabSmall0212GLTFShape.isPointerBlocker = true
stoneSlabSmall0212GLTFShape.visible = true
stoneSlabSmall0212.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const house6MBrown14 = new Entity("House 6 M Brown")
engine.addEntity(house6MBrown14)
const house6MBrown14transform = new Transform({
  position: new Vector3(22.25, 0, 7.25),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
house6MBrown14.addComponentOrReplace(house6MBrown14transform)
const house6MBrown14GLTFShape = new GLTFShape("models/house/House 6 M Brown.glb")
house6MBrown14GLTFShape.withCollisions = true
house6MBrown14GLTFShape.isPointerBlocker = true
house6MBrown14GLTFShape.visible = true
house6MBrown14.addComponentOrReplace(house6MBrown14GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0215 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0215)
const stoneSlabSmall0215transform = new Transform({
  position: new Vector3(19, 0, 7.5),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0215.addComponentOrReplace(stoneSlabSmall0215transform)
stoneSlabSmall0215.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0216 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0216)
const stoneSlabSmall0216transform = new Transform({
  position: new Vector3(19, 0, 2.5),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0216.addComponentOrReplace(stoneSlabSmall0216transform)
stoneSlabSmall0216.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0217 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0217)
const stoneSlabSmall0217transform = new Transform({
  position: new Vector3(19, 0, 5),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0217.addComponentOrReplace(stoneSlabSmall0217transform)
stoneSlabSmall0217.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0218 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0218)
const stoneSlabSmall0218transform = new Transform({
  position: new Vector3(19, 0, 10),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0218.addComponentOrReplace(stoneSlabSmall0218transform)
stoneSlabSmall0218.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0219 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0219)
const stoneSlabSmall0219transform = new Transform({
  position: new Vector3(19, 0, 12.5),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0219.addComponentOrReplace(stoneSlabSmall0219transform)
stoneSlabSmall0219.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0220 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0220)
const stoneSlabSmall0220transform = new Transform({
  position: new Vector3(22, 0, 4.5),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0220.addComponentOrReplace(stoneSlabSmall0220transform)
stoneSlabSmall0220.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0223 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0223)
const stoneSlabSmall0223transform = new Transform({
  position: new Vector3(16, 0, 5.5),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0223.addComponentOrReplace(stoneSlabSmall0223transform)
stoneSlabSmall0223.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0125 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0125)
const fenceWoodMedium0125transform = new Transform({
  position: new Vector3(12.75, 0, 0.75),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0125.addComponentOrReplace(fenceWoodMedium0125transform)
const fenceWoodMedium0125GLTFShape = new GLTFShape("models/fence/FenceWoodMedium_01.glb")
fenceWoodMedium0125GLTFShape.withCollisions = true
fenceWoodMedium0125GLTFShape.isPointerBlocker = true
fenceWoodMedium0125GLTFShape.visible = true
fenceWoodMedium0125.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0126 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0126)
const fenceWoodMedium0126transform = new Transform({
  position: new Vector3(9.75, 0, 0.75),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0126.addComponentOrReplace(fenceWoodMedium0126transform)
fenceWoodMedium0126.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0127 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0127)
const fenceWoodMedium0127transform = new Transform({
  position: new Vector3(6.75, 0, 0.75),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0127.addComponentOrReplace(fenceWoodMedium0127transform)
fenceWoodMedium0127.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0128 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0128)
const fenceWoodMedium0128transform = new Transform({
  position: new Vector3(3.75, 0, 0.75),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0128.addComponentOrReplace(fenceWoodMedium0128transform)
fenceWoodMedium0128.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0129 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0129)
const fenceWoodMedium0129transform = new Transform({
  position: new Vector3(0.75, 0, 0.75),
  rotation: new Quaternion(0, 1, 0, -7.450581E-08),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0129.addComponentOrReplace(fenceWoodMedium0129transform)
fenceWoodMedium0129.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0130 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0130)
const fenceWoodMedium0130transform = new Transform({
  position: new Vector3(0.75, 0, 3.75),
  rotation: new Quaternion(0, 1, 0, -7.450581E-08),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0130.addComponentOrReplace(fenceWoodMedium0130transform)
fenceWoodMedium0130.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0131 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0131)
const fenceWoodMedium0131transform = new Transform({
  position: new Vector3(0.75, 0, 6.75),
  rotation: new Quaternion(0, 1, 0, -7.450581E-08),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0131.addComponentOrReplace(fenceWoodMedium0131transform)
fenceWoodMedium0131.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0132 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0132)
const fenceWoodMedium0132transform = new Transform({
  position: new Vector3(0.75, 0, 9.75),
  rotation: new Quaternion(0, 1, 0, -7.450581E-08),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0132.addComponentOrReplace(fenceWoodMedium0132transform)
fenceWoodMedium0132.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0133 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0133)
const fenceWoodMedium0133transform = new Transform({
  position: new Vector3(0.75, 0, 12.75),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0133.addComponentOrReplace(fenceWoodMedium0133transform)
fenceWoodMedium0133.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0134 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0134)
const fenceWoodMedium0134transform = new Transform({
  position: new Vector3(3.75, 0, 12.75),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0134.addComponentOrReplace(fenceWoodMedium0134transform)
fenceWoodMedium0134.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0135 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0135)
const fenceWoodMedium0135transform = new Transform({
  position: new Vector3(6.75, 0, 12.75),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0135.addComponentOrReplace(fenceWoodMedium0135transform)
fenceWoodMedium0135.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0136 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0136)
const fenceWoodMedium0136transform = new Transform({
  position: new Vector3(9.75, 0, 12.75),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0136.addComponentOrReplace(fenceWoodMedium0136transform)
fenceWoodMedium0136.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0137 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0137)
const fenceWoodMedium0137transform = new Transform({
  position: new Vector3(12.75, 0, 12.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0137.addComponentOrReplace(fenceWoodMedium0137transform)
fenceWoodMedium0137.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0138 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0138)
const fenceWoodMedium0138transform = new Transform({
  position: new Vector3(12.75, 0, 3.75),
  rotation: new Quaternion(0, 4.470348E-08, 0, 1),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0138.addComponentOrReplace(fenceWoodMedium0138transform)
fenceWoodMedium0138.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeSycamore0340 = new Entity("Tree Sycamore 03")
engine.addEntity(treeSycamore0340)
const treeSycamore0340transform = new Transform({
  position: new Vector3(2.75, 0, 2.25),
  rotation: new Quaternion(0, 0.9914449, 0, 0.1305263),
  scale: new Vector3(1, 0.75, 1)
})
treeSycamore0340.addComponentOrReplace(treeSycamore0340transform)
const treeSycamore0340GLTFShape = new GLTFShape("models/treeSycamore/TreeSycamore_03/TreeSycamore_03.glb")
treeSycamore0340GLTFShape.withCollisions = true
treeSycamore0340GLTFShape.isPointerBlocker = true
treeSycamore0340GLTFShape.visible = true
treeSycamore0340.addComponentOrReplace(treeSycamore0340GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const store41 = new Entity("Store")
engine.addEntity(store41)
const store41transform = new Transform({
  position: new Vector3(9, 0, 10),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
store41.addComponentOrReplace(store41transform)
const store41GLTFShape = new GLTFShape("models/store/Store_02.glb")
store41GLTFShape.withCollisions = true
store41GLTFShape.isPointerBlocker = true
store41GLTFShape.visible = true
store41.addComponentOrReplace(store41GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cartBigClosed42 = new Entity("Cart Big Closed")
engine.addEntity(cartBigClosed42)
const cartBigClosed42transform = new Transform({
  position: new Vector3(4.5, 0, 9.75),
  rotation: new Quaternion(0, 0.5000001, 0, 0.8660254),
  scale: new Vector3(1, 1, 1)
})
cartBigClosed42.addComponentOrReplace(cartBigClosed42transform)
const cartBigClosed42GLTFShape = new GLTFShape("models/cartBig/Cart Big Closed.glb")
cartBigClosed42GLTFShape.withCollisions = true
cartBigClosed42GLTFShape.isPointerBlocker = true
cartBigClosed42GLTFShape.visible = true
cartBigClosed42.addComponentOrReplace(cartBigClosed42GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeSycamore0343 = new Entity("Tree Sycamore 03")
engine.addEntity(treeSycamore0343)
const treeSycamore0343transform = new Transform({
  position: new Vector3(2.25, 0, 12),
  rotation: new Quaternion(0, 0.7933534, 0, -0.6087615),
  scale: new Vector3(1, 1, 1)
})
treeSycamore0343.addComponentOrReplace(treeSycamore0343transform)
treeSycamore0343.addComponentOrReplace(treeSycamore0340GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const dirt244 = new Entity("Dirt2")
engine.addEntity(dirt244)
const dirt244transform = new Transform({
  position: new Vector3(11.25, 0, 2.25),
  rotation: new Quaternion(0, 0.9238796, 0, -0.3826834),
  scale: new Vector3(1, 1, 1)
})
dirt244.addComponentOrReplace(dirt244transform)
const dirt244GLTFShape = new GLTFShape("models/dirt/Dirt_04.glb")
dirt244GLTFShape.withCollisions = true
dirt244GLTFShape.isPointerBlocker = true
dirt244GLTFShape.visible = true
dirt244.addComponentOrReplace(dirt244GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const dirt345 = new Entity("Dirt3")
engine.addEntity(dirt345)
const dirt345transform = new Transform({
  position: new Vector3(8, 0, 3.75),
  rotation: new Quaternion(0, 0.6087615, 0, -0.7933534),
  scale: new Vector3(1, 1, 1)
})
dirt345.addComponentOrReplace(dirt345transform)
dirt345.addComponentOrReplace(dirt244GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const dirt146 = new Entity("Dirt1")
engine.addEntity(dirt146)
const dirt146transform = new Transform({
  position: new Vector3(10, 0, 6.25),
  rotation: new Quaternion(0, 0.258819, 0, 0.9659259),
  scale: new Vector3(1, 1, 1)
})
dirt146.addComponentOrReplace(dirt146transform)
dirt146.addComponentOrReplace(dirt244GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const dirt547 = new Entity("Dirt5")
engine.addEntity(dirt547)
const dirt547transform = new Transform({
  position: new Vector3(4.25, 0, 6.25),
  rotation: new Quaternion(0, 0.5000001, 0, -0.8660254),
  scale: new Vector3(1, 1, 1)
})
dirt547.addComponentOrReplace(dirt547transform)
dirt547.addComponentOrReplace(dirt244GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const dirt648 = new Entity("Dirt6")
engine.addEntity(dirt648)
const dirt648transform = new Transform({
  position: new Vector3(2, 0, 4.25),
  rotation: new Quaternion(0, 0.7933534, 0, -0.6087615),
  scale: new Vector3(1, 1, 1)
})
dirt648.addComponentOrReplace(dirt648transform)
dirt648.addComponentOrReplace(dirt244GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const dirt449 = new Entity("Dirt4")
engine.addEntity(dirt449)
const dirt449transform = new Transform({
  position: new Vector3(5, 0, 2.25),
  rotation: new Quaternion(0, 0.9659259, 0, -0.258819),
  scale: new Vector3(1, 1, 1)
})
dirt449.addComponentOrReplace(dirt449transform)
dirt449.addComponentOrReplace(dirt244GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir0250 = new Entity("Tree Fir 02")
engine.addEntity(treeFir0250)
const treeFir0250transform = new Transform({
  position: new Vector3(20.25, 0, 1.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.75, 0.5, 0.75)
})
treeFir0250.addComponentOrReplace(treeFir0250transform)
const treeFir0250GLTFShape = new GLTFShape("models/treeFir/TreeFir_02.glb")
treeFir0250GLTFShape.withCollisions = true
treeFir0250GLTFShape.isPointerBlocker = true
treeFir0250GLTFShape.visible = true
treeFir0250.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeSycamore0351 = new Entity("Tree Sycamore 03")
engine.addEntity(treeSycamore0351)
const treeSycamore0351transform = new Transform({
  position: new Vector3(20.25, 0, 8.25),
  rotation: new Quaternion(0, 0.9914449, 0, 0.1305263),
  scale: new Vector3(1, 1, 1)
})
treeSycamore0351.addComponentOrReplace(treeSycamore0351transform)
treeSycamore0351.addComponentOrReplace(treeSycamore0340GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0252 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0252)
const stoneSlabSmall0252transform = new Transform({
  position: new Vector3(22, 0, 10),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0252.addComponentOrReplace(stoneSlabSmall0252transform)
stoneSlabSmall0252.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeSycamore0354 = new Entity("Tree Sycamore 03")
engine.addEntity(treeSycamore0354)
const treeSycamore0354transform = new Transform({
  position: new Vector3(14, 0, 10.5),
  rotation: new Quaternion(0, 1, 0, -2.533197E-07),
  scale: new Vector3(0.75, 0.75, 0.75)
})
treeSycamore0354.addComponentOrReplace(treeSycamore0354transform)
treeSycamore0354.addComponentOrReplace(treeSycamore0340GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const well55 = new Entity("Well")
engine.addEntity(well55)
const well55transform = new Transform({
  position: new Vector3(23.5, 0, 11.25),
  rotation: new Quaternion(0, 0.3826835, 0, 0.9238795),
  scale: new Vector3(1.5, 1.25, 1.5)
})
well55.addComponentOrReplace(well55transform)
const well55GLTFShape = new GLTFShape("models/well/Well_01.glb")
well55GLTFShape.withCollisions = true
well55GLTFShape.isPointerBlocker = true
well55GLTFShape.visible = true
well55.addComponentOrReplace(well55GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const logs256 = new Entity("Logs 2")
engine.addEntity(logs256)
const logs256transform = new Transform({
  position: new Vector3(28.75, 0, 8.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.5, 2.5, 2.5)
})
logs256.addComponentOrReplace(logs256transform)
const logs256GLTFShape = new GLTFShape("models/logPile/Logs 2.glb")
logs256GLTFShape.withCollisions = true
logs256GLTFShape.isPointerBlocker = true
logs256GLTFShape.visible = true
logs256.addComponentOrReplace(logs256GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const axe257 = new Entity("Axe 2")
engine.addEntity(axe257)
const axe257transform = new Transform({
  position: new Vector3(28.75, 0, 11.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
axe257.addComponentOrReplace(axe257transform)
const axe257GLTFShape = new GLTFShape("models/axe/Axe 2.glb")
axe257GLTFShape.withCollisions = true
axe257GLTFShape.isPointerBlocker = true
axe257GLTFShape.visible = true
axe257.addComponentOrReplace(axe257GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const outdoorBoxLamp59 = new Entity("Outdoor Box Lamp")
engine.addEntity(outdoorBoxLamp59)
const outdoorBoxLamp59transform = new Transform({
  position: new Vector3(22.25, 2, 6.75),
  rotation: new Quaternion(0, 0.7071069, 0, -0.7071068),
  scale: new Vector3(0.75, 0.75, 0.75)
})
outdoorBoxLamp59.addComponentOrReplace(outdoorBoxLamp59transform)
const outdoorBoxLamp59GLTFShape = new GLTFShape("models/outdoorLamp/Outdoor Box Lamp.glb")
outdoorBoxLamp59GLTFShape.withCollisions = true
outdoorBoxLamp59GLTFShape.isPointerBlocker = true
outdoorBoxLamp59GLTFShape.visible = true
outdoorBoxLamp59.addComponentOrReplace(outdoorBoxLamp59GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const window2x2V2Closed60 = new Entity("Window 2x2 V2 Closed")
engine.addEntity(window2x2V2Closed60)
const window2x2V2Closed60transform = new Transform({
  position: new Vector3(22.25, 4, 6.25),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071069),
  scale: new Vector3(1, 1, 1)
})
window2x2V2Closed60.addComponentOrReplace(window2x2V2Closed60transform)
const window2x2V2Closed60GLTFShape = new GLTFShape("models/windowClosed/Window 2x2 V2 Closed.glb")
window2x2V2Closed60GLTFShape.withCollisions = true
window2x2V2Closed60GLTFShape.isPointerBlocker = true
window2x2V2Closed60GLTFShape.visible = true
window2x2V2Closed60.addComponentOrReplace(window2x2V2Closed60GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const window2x2V2Closed61 = new Entity("Window 2x2 V2 Closed")
engine.addEntity(window2x2V2Closed61)
const window2x2V2Closed61transform = new Transform({
  position: new Vector3(22.25, 4, 3.25),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071069),
  scale: new Vector3(1, 1, 1)
})
window2x2V2Closed61.addComponentOrReplace(window2x2V2Closed61transform)
window2x2V2Closed61.addComponentOrReplace(window2x2V2Closed60GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const window2x2V2Closed62 = new Entity("Window 2x2 V2 Closed")
engine.addEntity(window2x2V2Closed62)
const window2x2V2Closed62transform = new Transform({
  position: new Vector3(31.25, 4, 5.25),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
window2x2V2Closed62.addComponentOrReplace(window2x2V2Closed62transform)
window2x2V2Closed62.addComponentOrReplace(window2x2V2Closed60GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const window2x2V2Closed63 = new Entity("Window 2x2 V2 Closed")
engine.addEntity(window2x2V2Closed63)
const window2x2V2Closed63transform = new Transform({
  position: new Vector3(31.25, 4, 2.25),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
window2x2V2Closed63.addComponentOrReplace(window2x2V2Closed63transform)
window2x2V2Closed63.addComponentOrReplace(window2x2V2Closed60GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const shovel64 = new Entity("Shovel")
engine.addEntity(shovel64)
const shovel64transform = new Transform({
  position: new Vector3(7.75, 0, 1.5),
  rotation: new Quaternion(-0.2981333, -0.1244852, -0.03925003, 0.9455578),
  scale: new Vector3(1.25, 1, 1)
})
shovel64.addComponentOrReplace(shovel64transform)
const shovel64GLTFShape = new GLTFShape("models/shovel/Shovel.glb")
shovel64GLTFShape.withCollisions = true
shovel64GLTFShape.isPointerBlocker = true
shovel64GLTFShape.visible = true
shovel64.addComponentOrReplace(shovel64GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const window2x2V2Closed65 = new Entity("Window 2x2 V2 Closed")
engine.addEntity(window2x2V2Closed65)
const window2x2V2Closed65transform = new Transform({
  position: new Vector3(23.2, 3, 1.25),
  rotation: new Quaternion(0, 1, 0, -7.450581E-08),
  scale: new Vector3(1, 1.3, 1)
})
window2x2V2Closed65.addComponentOrReplace(window2x2V2Closed65transform)
window2x2V2Closed65.addComponentOrReplace(window2x2V2Closed60GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const flower0166 = new Entity("Flower 01")
engine.addEntity(flower0166)
const flower0166transform = new Transform({
  position: new Vector3(9.45, 1.3, 10.6),
  rotation: new Quaternion(-0.258819, 0, 0, 0.9659259),
  scale: new Vector3(0.75, 0.75, 0.75)
})
flower0166.addComponentOrReplace(flower0166transform)
const flower0166GLTFShape = new GLTFShape("models/sunflower/Flower_01.glb")
flower0166GLTFShape.withCollisions = true
flower0166GLTFShape.isPointerBlocker = true
flower0166GLTFShape.visible = true
flower0166.addComponentOrReplace(flower0166GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const flower0167 = new Entity("Flower 01")
engine.addEntity(flower0167)
const flower0167transform = new Transform({
  position: new Vector3(11.3, 1.3, 10.6),
  rotation: new Quaternion(-0.258819, 0, 0, 0.9659259),
  scale: new Vector3(0.75, 0.75, 0.75)
})
flower0167.addComponentOrReplace(flower0167transform)
flower0167.addComponentOrReplace(flower0166GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const rockBig0772 = new Entity("Rock Big 07")
engine.addEntity(rockBig0772)
const rockBig0772transform = new Transform({
  position: new Vector3(27.5, 0, 25.5),
  rotation: new Quaternion(0, 0.6087614, 0, 0.7933534),
  scale: new Vector3(1.5, 1.5, 1)
})
rockBig0772.addComponentOrReplace(rockBig0772transform)
const rockBig0772GLTFShape = new GLTFShape("models/rockWithMoss/RockBig_07/RockBig_07.glb")
rockBig0772GLTFShape.withCollisions = true
rockBig0772GLTFShape.isPointerBlocker = true
rockBig0772GLTFShape.visible = true
rockBig0772.addComponentOrReplace(rockBig0772GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const rockBig0773 = new Entity("Rock Big 07")
engine.addEntity(rockBig0773)
const rockBig0773transform = new Transform({
  position: new Vector3(22, 0, 27),
  rotation: new Quaternion(0, 1, 0, -5.960464E-08),
  scale: new Vector3(1.25, 1, 1)
})
rockBig0773.addComponentOrReplace(rockBig0773transform)
rockBig0773.addComponentOrReplace(rockBig0772GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pond74 = new Entity("Pond")
engine.addEntity(pond74)
const pond74transform = new Transform({
  position: new Vector3(22.5, 0, 20),
  rotation: new Quaternion(0, 0.5000001, 0, -0.8660254),
  scale: new Vector3(1.5, 1, 1.5)
})
pond74.addComponentOrReplace(pond74transform)
const pond74GLTFShape = new GLTFShape("models/pond/Pond_02.glb")
pond74GLTFShape.withCollisions = true
pond74GLTFShape.isPointerBlocker = true
pond74GLTFShape.visible = true
pond74.addComponentOrReplace(pond74GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const rockBig0775 = new Entity("Rock Big 07")
engine.addEntity(rockBig0775)
const rockBig0775transform = new Transform({
  position: new Vector3(28.75, 0, 18.5),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1.25, 0.75, 0.75)
})
rockBig0775.addComponentOrReplace(rockBig0775transform)
rockBig0775.addComponentOrReplace(rockBig0772GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0276 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0276)
const stoneSlabSmall0276transform = new Transform({
  position: new Vector3(17.75, 0, 15),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0276.addComponentOrReplace(stoneSlabSmall0276transform)
stoneSlabSmall0276.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const wellBucket277 = new Entity("Well Bucket2")
engine.addEntity(wellBucket277)
const wellBucket277transform = new Transform({
  position: new Vector3(22.25, 0, 12.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
wellBucket277.addComponentOrReplace(wellBucket277transform)
const wellBucket277GLTFShape = new GLTFShape("models/bucket/Well Bucket.glb")
wellBucket277GLTFShape.withCollisions = true
wellBucket277GLTFShape.isPointerBlocker = true
wellBucket277GLTFShape.visible = true
wellBucket277.addComponentOrReplace(wellBucket277GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const wellBucket378 = new Entity("Well Bucket3")
engine.addEntity(wellBucket378)
const wellBucket378transform = new Transform({
  position: new Vector3(21.5, 0, 10.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
wellBucket378.addComponentOrReplace(wellBucket378transform)
wellBucket378.addComponentOrReplace(wellBucket277GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const wellBucket179 = new Entity("Well Bucket1")
engine.addEntity(wellBucket179)
const wellBucket179transform = new Transform({
  position: new Vector3(23.25, 0, 13.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
wellBucket179.addComponentOrReplace(wellBucket179transform)
wellBucket179.addComponentOrReplace(wellBucket277GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const shovel83 = new Entity("Shovel")
engine.addEntity(shovel83)
const shovel83transform = new Transform({
  position: new Vector3(7.75, 0.05, 6.25),
  rotation: new Quaternion(0.1830127, -0.6830127, -0.6830127, -0.1830127),
  scale: new Vector3(1.25, 1, 1)
})
shovel83.addComponentOrReplace(shovel83transform)
shovel83.addComponentOrReplace(shovel64GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass018 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass018)
const floorBaseGrass018transform = new Transform({
  position: new Vector3(8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass018.addComponentOrReplace(floorBaseGrass018transform)
floorBaseGrass018.addComponentOrReplace(floorBaseGrass017GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const signGarden111 = new Entity("Sign Garden")
engine.addEntity(signGarden111)
const signGarden111transform = new Transform({
  position: new Vector3(13.25, 0, 3.25),
  rotation: new Quaternion(0, 0.6087615, 0, 0.7933534),
  scale: new Vector3(1, 1, 1)
})
signGarden111.addComponentOrReplace(signGarden111transform)
const signGarden111GLTFShape = new GLTFShape("models/sign/Signpost_Root.glb")
signGarden111GLTFShape.withCollisions = true
signGarden111GLTFShape.isPointerBlocker = true
signGarden111GLTFShape.visible = true
signGarden111.addComponentOrReplace(signGarden111GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir02114 = new Entity("Tree Fir 02")
engine.addEntity(treeFir02114)
const treeFir02114transform = new Transform({
  position: new Vector3(25, 0, 15),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
treeFir02114.addComponentOrReplace(treeFir02114transform)
treeFir02114.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir02115 = new Entity("Tree Fir 02")
engine.addEntity(treeFir02115)
const treeFir02115transform = new Transform({
  position: new Vector3(29.5, 0, 13.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.75, 0.5, 0.75)
})
treeFir02115.addComponentOrReplace(treeFir02115transform)
treeFir02115.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir02116 = new Entity("Tree Fir 02")
engine.addEntity(treeFir02116)
const treeFir02116transform = new Transform({
  position: new Vector3(15.75, 0, 26.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.75, 1.75, 1.75)
})
treeFir02116.addComponentOrReplace(treeFir02116transform)
treeFir02116.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir02117 = new Entity("Tree Fir 02")
engine.addEntity(treeFir02117)
const treeFir02117transform = new Transform({
  position: new Vector3(18, 0, 23.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
treeFir02117.addComponentOrReplace(treeFir02117transform)
treeFir02117.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const window2x2V2Closed121 = new Entity("Window 2x2 V2 Closed")
engine.addEntity(window2x2V2Closed121)
const window2x2V2Closed121transform = new Transform({
  position: new Vector3(22.25, 0.5, 4.25),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1.9, 1.2, 1)
})
window2x2V2Closed121.addComponentOrReplace(window2x2V2Closed121transform)
window2x2V2Closed121.addComponentOrReplace(window2x2V2Closed60GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const outdoorBoxLamp124 = new Entity("Outdoor Box Lamp")
engine.addEntity(outdoorBoxLamp124)
const outdoorBoxLamp124transform = new Transform({
  position: new Vector3(22.25, 2, 4.75),
  rotation: new Quaternion(0, 0.7071069, 0, -0.7071068),
  scale: new Vector3(0.75, 0.75, 0.75)
})
outdoorBoxLamp124.addComponentOrReplace(outdoorBoxLamp124transform)
outdoorBoxLamp124.addComponentOrReplace(outdoorBoxLamp59GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const couch126 = new Entity("couch")
engine.addEntity(couch126)
const couch126transform = new Transform({
  position: new Vector3(25.25, 0.6, 5.75),
  rotation: new Quaternion(0, 1, 0, -7.450581E-08),
  scale: new Vector3(1, 1, 1)
})
couch126.addComponentOrReplace(couch126transform)
const couch126GLTFShape = new GLTFShape("models/couch/ThreeSeater_Couch.glb")
couch126GLTFShape.withCollisions = true
couch126GLTFShape.isPointerBlocker = true
couch126GLTFShape.visible = true
couch126.addComponentOrReplace(couch126GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const bed136 = new Entity("bed")
engine.addEntity(bed136)
const bed136transform = new Transform({
  position: new Vector3(26.25, 3.6, 7.1),
  rotation: new Quaternion(0, 1, 0, -7.450581E-08),
  scale: new Vector3(1, 1, 1)
})
bed136.addComponentOrReplace(bed136transform)
const bed136GLTFShape = new GLTFShape("models/bed/Bed King.glb")
bed136GLTFShape.withCollisions = true
bed136GLTFShape.isPointerBlocker = true
bed136GLTFShape.visible = true
bed136.addComponentOrReplace(bed136GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const chest138 = new Entity("Chest")
engine.addEntity(chest138)
const chest138transform = new Transform({
  position: new Vector3(30.5, 3.6, 2.4),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
chest138.addComponentOrReplace(chest138transform)
const chest138GLTFShape = new GLTFShape("models/chest/Chest_Genesis.glb")
chest138GLTFShape.withCollisions = true
chest138GLTFShape.isPointerBlocker = true
chest138GLTFShape.visible = true
chest138.addComponentOrReplace(chest138GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const door154 = new Entity("Door")
engine.addEntity(door154)
const door154transform = new Transform({
  position: new Vector3(22.26, 0, 6.26),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1.02, 1.01, 1)
})
door154.addComponentOrReplace(door154transform)
const door154GLTFShape = new GLTFShape("models/door/Door 1.glb")
door154GLTFShape.withCollisions = true
door154GLTFShape.isPointerBlocker = true
door154GLTFShape.visible = true
door154.addComponentOrReplace(door154GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeSycamore03155 = new Entity("Tree Sycamore 03")
engine.addEntity(treeSycamore03155)
const treeSycamore03155transform = new Transform({
  position: new Vector3(2.25, 0, 24),
  rotation: new Quaternion(0, 0.7933534, 0, -0.6087615),
  scale: new Vector3(1.25, 1.25, 1.25)
})
treeSycamore03155.addComponentOrReplace(treeSycamore03155transform)
treeSycamore03155.addComponentOrReplace(treeSycamore0340GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeSycamore03156 = new Entity("Tree Sycamore 03")
engine.addEntity(treeSycamore03156)
const treeSycamore03156transform = new Transform({
  position: new Vector3(9.5, 0, 15),
  rotation: new Quaternion(0, 1, 0, -7.450581E-08),
  scale: new Vector3(1.25, 1.25, 1.25)
})
treeSycamore03156.addComponentOrReplace(treeSycamore03156transform)
treeSycamore03156.addComponentOrReplace(treeSycamore0340GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeSycamore03157 = new Entity("Tree Sycamore 03")
engine.addEntity(treeSycamore03157)
const treeSycamore03157transform = new Transform({
  position: new Vector3(8.25, 0, 27.75),
  rotation: new Quaternion(0, 0.9914449, 0, 0.1305263),
  scale: new Vector3(1.25, 1.25, 1.25)
})
treeSycamore03157.addComponentOrReplace(treeSycamore03157transform)
treeSycamore03157.addComponentOrReplace(treeSycamore0340GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeSycamore03158 = new Entity("Tree Sycamore 03")
engine.addEntity(treeSycamore03158)
const treeSycamore03158transform = new Transform({
  position: new Vector3(5, 0, 18.5),
  rotation: new Quaternion(0, 0.7933534, 0, -0.6087615),
  scale: new Vector3(1.75, 1.75, 1.75)
})
treeSycamore03158.addComponentOrReplace(treeSycamore03158transform)
treeSycamore03158.addComponentOrReplace(treeSycamore0340GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeSycamore03159 = new Entity("Tree Sycamore 03")
engine.addEntity(treeSycamore03159)
const treeSycamore03159transform = new Transform({
  position: new Vector3(12.5, 0, 20),
  rotation: new Quaternion(0, 0.7933534, 0, -0.6087615),
  scale: new Vector3(1, 1, 1)
})
treeSycamore03159.addComponentOrReplace(treeSycamore03159transform)
treeSycamore03159.addComponentOrReplace(treeSycamore0340GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir02160 = new Entity("Tree Fir 02")
engine.addEntity(treeFir02160)
const treeFir02160transform = new Transform({
  position: new Vector3(10.75, 0, 30.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 1.5, 1.5)
})
treeFir02160.addComponentOrReplace(treeFir02160transform)
treeFir02160.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir02161 = new Entity("Tree Fir 02")
engine.addEntity(treeFir02161)
const treeFir02161transform = new Transform({
  position: new Vector3(10, 0, 23.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 1.5, 1.5)
})
treeFir02161.addComponentOrReplace(treeFir02161transform)
treeFir02161.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir02162 = new Entity("Tree Fir 02")
engine.addEntity(treeFir02162)
const treeFir02162transform = new Transform({
  position: new Vector3(1.75, 0, 17.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 1.5, 1.5)
})
treeFir02162.addComponentOrReplace(treeFir02162transform)
treeFir02162.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir02163 = new Entity("Tree Fir 02")
engine.addEntity(treeFir02163)
const treeFir02163transform = new Transform({
  position: new Vector3(5, 0, 14),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.25, 1.25, 1.25)
})
treeFir02163.addComponentOrReplace(treeFir02163transform)
treeFir02163.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir02164 = new Entity("Tree Fir 02")
engine.addEntity(treeFir02164)
const treeFir02164transform = new Transform({
  position: new Vector3(14, 0, 23.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.25, 1.25, 1.25)
})
treeFir02164.addComponentOrReplace(treeFir02164transform)
treeFir02164.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir02165 = new Entity("Tree Fir 02")
engine.addEntity(treeFir02165)
const treeFir02165transform = new Transform({
  position: new Vector3(13.25, 0, 14.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.25, 1.25, 1.25)
})
treeFir02165.addComponentOrReplace(treeFir02165transform)
treeFir02165.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir02166 = new Entity("Tree Fir 02")
engine.addEntity(treeFir02166)
const treeFir02166transform = new Transform({
  position: new Vector3(17, 0, 19),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.25, 1.25, 1.25)
})
treeFir02166.addComponentOrReplace(treeFir02166transform)
treeFir02166.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir02168 = new Entity("Tree Fir 02")
engine.addEntity(treeFir02168)
const treeFir02168transform = new Transform({
  position: new Vector3(9, 0, 18.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.25, 1.25, 1.25)
})
treeFir02168.addComponentOrReplace(treeFir02168transform)
treeFir02168.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir02169 = new Entity("Tree Fir 02")
engine.addEntity(treeFir02169)
const treeFir02169transform = new Transform({
  position: new Vector3(2, 0, 29.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.75, 1.75, 1.75)
})
treeFir02169.addComponentOrReplace(treeFir02169transform)
treeFir02169.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir02170 = new Entity("Tree Fir 02")
engine.addEntity(treeFir02170)
const treeFir02170transform = new Transform({
  position: new Vector3(5.5, 0, 23.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.75, 1.75, 1.75)
})
treeFir02170.addComponentOrReplace(treeFir02170transform)
treeFir02170.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const chair1175 = new Entity("Chair 1")
engine.addEntity(chair1175)
const chair1175transform = new Transform({
  position: new Vector3(24, 0.6, 3.14),
  rotation: new Quaternion(0, 0.9659259, 0, 0.2588191),
  scale: new Vector3(1, 1, 1)
})
chair1175.addComponentOrReplace(chair1175transform)
const chair1175GLTFShape = new GLTFShape("models/chair/Chair 1.glb")
chair1175GLTFShape.withCollisions = true
chair1175GLTFShape.isPointerBlocker = true
chair1175GLTFShape.visible = true
chair1175.addComponentOrReplace(chair1175GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const map03176 = new Entity("Map 03")
engine.addEntity(map03176)
const map03176transform = new Transform({
  position: new Vector3(23.75, 1.63, 2.25),
  rotation: new Quaternion(0, 0.1305262, 0, 0.9914449),
  scale: new Vector3(1, 1, 1)
})
map03176.addComponentOrReplace(map03176transform)
const map03176GLTFShape = new GLTFShape("models/paper/Map_03.glb")
map03176GLTFShape.withCollisions = true
map03176GLTFShape.isPointerBlocker = true
map03176GLTFShape.visible = true
map03176.addComponentOrReplace(map03176GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const chair1179 = new Entity("Chair 1")
engine.addEntity(chair1179)
const chair1179transform = new Transform({
  position: new Vector3(24, 3.6, 6),
  rotation: new Quaternion(0, 0.9238796, 0, -0.3826834),
  scale: new Vector3(1, 1, 1)
})
chair1179.addComponentOrReplace(chair1179transform)
chair1179.addComponentOrReplace(chair1175GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const gem1180 = new Entity("Gem1")
engine.addEntity(gem1180)
const gem1180transform = new Transform({
  position: new Vector3(28, 0.6, 6.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
gem1180.addComponentOrReplace(gem1180transform)
const gem1180GLTFShape = new GLTFShape("models/gem/Gem_03.glb")
gem1180GLTFShape.withCollisions = true
gem1180GLTFShape.isPointerBlocker = true
gem1180GLTFShape.visible = true
gem1180.addComponentOrReplace(gem1180GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const gem3181 = new Entity("Gem3")
engine.addEntity(gem3181)
const gem3181transform = new Transform({
  position: new Vector3(23.7, 1.4, 1.55),
  rotation: new Quaternion(0.4999999, -0.4999999, -0.5000001, 0.5000001),
  scale: new Vector3(1, 1, 1)
})
gem3181.addComponentOrReplace(gem3181transform)
gem3181.addComponentOrReplace(gem1180GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const gem5184 = new Entity("Gem5")
engine.addEntity(gem5184)
const gem5184transform = new Transform({
  position: new Vector3(27.5, 3.75, 6.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
gem5184.addComponentOrReplace(gem5184transform)
gem5184.addComponentOrReplace(gem1180GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const gem4185 = new Entity("Gem4")
engine.addEntity(gem4185)
const gem4185transform = new Transform({
  position: new Vector3(30.5, 3.7, 2.5),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071069),
  scale: new Vector3(1, 1, 1)
})
gem4185.addComponentOrReplace(gem4185transform)
gem4185.addComponentOrReplace(gem1180GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const carpet02187 = new Entity("Carpet 02")
engine.addEntity(carpet02187)
const carpet02187transform = new Transform({
  position: new Vector3(26.75, 0.75, 4.75),
  rotation: new Quaternion(0, -0.1305261, 0, 0.9914449),
  scale: new Vector3(1, 1, 1)
})
carpet02187.addComponentOrReplace(carpet02187transform)
const carpet02187GLTFShape = new GLTFShape("models/carpet/Carpet_02.glb")
carpet02187GLTFShape.withCollisions = true
carpet02187GLTFShape.isPointerBlocker = true
carpet02187GLTFShape.visible = true
carpet02187.addComponentOrReplace(carpet02187GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const table4188 = new Entity("Table 4")
engine.addEntity(table4188)
const table4188transform = new Transform({
  position: new Vector3(23, 3.7, 5.75),
  rotation: new Quaternion(0, 4.470348E-08, 0, 1),
  scale: new Vector3(1, 1.75, 1.25)
})
table4188.addComponentOrReplace(table4188transform)
const table4188GLTFShape = new GLTFShape("models/table/Table 4.glb")
table4188GLTFShape.withCollisions = true
table4188GLTFShape.isPointerBlocker = true
table4188GLTFShape.visible = true
table4188.addComponentOrReplace(table4188GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const bench4189 = new Entity("Bench 4")
engine.addEntity(bench4189)
const bench4189transform = new Transform({
  position: new Vector3(30.25, 0.6, 5.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.25, 1.75, 2.25)
})
bench4189.addComponentOrReplace(bench4189transform)
const bench4189GLTFShape = new GLTFShape("models/bench/Bench 4.glb")
bench4189GLTFShape.withCollisions = true
bench4189GLTFShape.isPointerBlocker = true
bench4189GLTFShape.visible = true
bench4189.addComponentOrReplace(bench4189GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const vase1190 = new Entity("Vase 1")
engine.addEntity(vase1190)
const vase1190transform = new Transform({
  position: new Vector3(30.25, 1.23, 5.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
vase1190.addComponentOrReplace(vase1190transform)
const vase1190GLTFShape = new GLTFShape("models/vase/Vase 1.glb")
vase1190GLTFShape.withCollisions = true
vase1190GLTFShape.isPointerBlocker = true
vase1190GLTFShape.visible = true
vase1190.addComponentOrReplace(vase1190GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const hwn20Candle02191 = new Entity("HWN20 Candle 02")
engine.addEntity(hwn20Candle02191)
const hwn20Candle02191transform = new Transform({
  position: new Vector3(24.5, 1.63, 2.25),
  rotation: new Quaternion(0, 0.5000001, 0, -0.8660254),
  scale: new Vector3(1, 0.5, 1)
})
hwn20Candle02191.addComponentOrReplace(hwn20Candle02191transform)
const hwn20Candle02191GLTFShape = new GLTFShape("models/candle/HWN20_Candle_02.glb")
hwn20Candle02191GLTFShape.withCollisions = true
hwn20Candle02191GLTFShape.isPointerBlocker = true
hwn20Candle02191GLTFShape.visible = true
hwn20Candle02191.addComponentOrReplace(hwn20Candle02191GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const hwn20Candle02192 = new Entity("HWN20 Candle 02")
engine.addEntity(hwn20Candle02192)
const hwn20Candle02192transform = new Transform({
  position: new Vector3(24.75, 1.63, 2),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
hwn20Candle02192.addComponentOrReplace(hwn20Candle02192transform)
hwn20Candle02192.addComponentOrReplace(hwn20Candle02191GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const hwn20Candle02193 = new Entity("HWN20 Candle 02")
engine.addEntity(hwn20Candle02193)
const hwn20Candle02193transform = new Transform({
  position: new Vector3(24.9, 1.63, 2.4),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071069),
  scale: new Vector3(0.75, 0.75, 0.75)
})
hwn20Candle02193.addComponentOrReplace(hwn20Candle02193transform)
hwn20Candle02193.addComponentOrReplace(hwn20Candle02191GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const flower01194 = new Entity("Flower 01")
engine.addEntity(flower01194)
const flower01194transform = new Transform({
  position: new Vector3(30.25, 1.8, 5.35),
  rotation: new Quaternion(0.4393611, -0.8344634, -0.07851224, 0.3232159),
  scale: new Vector3(1, 1, 1)
})
flower01194.addComponentOrReplace(flower01194transform)
flower01194.addComponentOrReplace(flower0166GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const flower01197 = new Entity("Flower 01")
engine.addEntity(flower01197)
const flower01197transform = new Transform({
  position: new Vector3(30.33, 1.8, 5.25),
  rotation: new Quaternion(-0.3251486, -0.5101339, -0.424532, 0.6736575),
  scale: new Vector3(1, 1, 1)
})
flower01197.addComponentOrReplace(flower01197transform)
flower01197.addComponentOrReplace(flower0166GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const flower01198 = new Entity("Flower 01")
engine.addEntity(flower01198)
const flower01198transform = new Transform({
  position: new Vector3(30.25, 1.8, 5.15),
  rotation: new Quaternion(-0.2377531, -0.4506524, 0.2853648, 0.8117591),
  scale: new Vector3(1, 1, 1)
})
flower01198.addComponentOrReplace(flower01198transform)
flower01198.addComponentOrReplace(flower0166GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const gem2200 = new Entity("Gem2")
engine.addEntity(gem2200)
const gem2200transform = new Transform({
  position: new Vector3(30.27, 1.87, 5.2),
  rotation: new Quaternion(0.4304593, 0.2705981, 0.5609855, 0.6532815),
  scale: new Vector3(1, 1, 1)
})
gem2200.addComponentOrReplace(gem2200transform)
gem2200.addComponentOrReplace(gem1180GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const table4201 = new Entity("Table 4")
engine.addEntity(table4201)
const table4201transform = new Transform({
  position: new Vector3(24.25, 0.7, 2.25),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1.75, 1.25)
})
table4201.addComponentOrReplace(table4201transform)
table4201.addComponentOrReplace(table4188GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const map03202 = new Entity("Map 03")
engine.addEntity(map03202)
const map03202transform = new Transform({
  position: new Vector3(23.1, 4.63, 5.25),
  rotation: new Quaternion(0, 0.5, 0, 0.8660254),
  scale: new Vector3(1, 1, 1)
})
map03202.addComponentOrReplace(map03202transform)
map03202.addComponentOrReplace(map03176GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const vase1203 = new Entity("Vase 1")
engine.addEntity(vase1203)
const vase1203transform = new Transform({
  position: new Vector3(23, 4.63, 6.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
vase1203.addComponentOrReplace(vase1203transform)
vase1203.addComponentOrReplace(vase1190GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const plant03204 = new Entity("Plant 03")
engine.addEntity(plant03204)
const plant03204transform = new Transform({
  position: new Vector3(23.08, 5.1, 6.29),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 0.75, 1)
})
plant03204.addComponentOrReplace(plant03204transform)
const plant03204GLTFShape = new GLTFShape("models/tulip/Plant_03.glb")
plant03204GLTFShape.withCollisions = true
plant03204GLTFShape.isPointerBlocker = true
plant03204GLTFShape.visible = true
plant03204.addComponentOrReplace(plant03204GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const plant03205 = new Entity("Plant 03")
engine.addEntity(plant03205)
const plant03205transform = new Transform({
  position: new Vector3(22.9, 5.1, 6.29),
  rotation: new Quaternion(0, 0.9396927, 0, -0.3420202),
  scale: new Vector3(1, 0.75, 1)
})
plant03205.addComponentOrReplace(plant03205transform)
plant03205.addComponentOrReplace(plant03204GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const bench4206 = new Entity("Bench 4")
engine.addEntity(bench4206)
const bench4206transform = new Transform({
  position: new Vector3(28.75, 4, 6),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1.5, 1.5, 1.5)
})
bench4206.addComponentOrReplace(bench4206transform)
bench4206.addComponentOrReplace(bench4189GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const candle207 = new Entity("candle")
engine.addEntity(candle207)
const candle207transform = new Transform({
  position: new Vector3(28.8, 4.54, 6.1),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
candle207.addComponentOrReplace(candle207transform)
candle207.addComponentOrReplace(hwn20Candle02191GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const hwn20Candle02208 = new Entity("HWN20 Candle 02")
engine.addEntity(hwn20Candle02208)
const hwn20Candle02208transform = new Transform({
  position: new Vector3(28.75, 4.54, 5.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.75, 0.5, 0.75)
})
hwn20Candle02208.addComponentOrReplace(hwn20Candle02208transform)
hwn20Candle02208.addComponentOrReplace(hwn20Candle02191GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lilyPad01211 = new Entity("Lily Pad 01")
engine.addEntity(lilyPad01211)
const lilyPad01211transform = new Transform({
  position: new Vector3(21.75, 0.1, 22),
  rotation: new Quaternion(0, 0.3826835, 0, 0.9238795),
  scale: new Vector3(1.5, 1, 1)
})
lilyPad01211.addComponentOrReplace(lilyPad01211transform)
const lilyPad01211GLTFShape = new GLTFShape("models/lilyPad/LilyPad_01.glb")
lilyPad01211GLTFShape.withCollisions = true
lilyPad01211GLTFShape.isPointerBlocker = true
lilyPad01211GLTFShape.visible = true
lilyPad01211.addComponentOrReplace(lilyPad01211GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lilyPad01212 = new Entity("Lily Pad 01")
engine.addEntity(lilyPad01212)
const lilyPad01212transform = new Transform({
  position: new Vector3(20.25, 0.25, 22),
  rotation: new Quaternion(0, 0.9659259, 0, 0.2588191),
  scale: new Vector3(1, 1, 1)
})
lilyPad01212.addComponentOrReplace(lilyPad01212transform)
lilyPad01212.addComponentOrReplace(lilyPad01211GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const lilyPad01213 = new Entity("Lily Pad 01")
engine.addEntity(lilyPad01213)
const lilyPad01213transform = new Transform({
  position: new Vector3(19.75, 0.1, 20.75),
  rotation: new Quaternion(0, 0.9914449, 0, 0.1305263),
  scale: new Vector3(1.25, 1, 1.25)
})
lilyPad01213.addComponentOrReplace(lilyPad01213transform)
lilyPad01213.addComponentOrReplace(lilyPad01211GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
  store:{
    entity: store41,
    transform: store41transform,
    GLTFShape: store41GLTFShape,
  },
  dirt2:{
    entity: dirt244,
    transform: dirt244transform,
    GLTFShape: dirt244GLTFShape,
  },
  dirt3:{
    entity: dirt345,
    transform: dirt345transform,
    GLTFShape: dirt244GLTFShape,
  },
  dirt1:{
    entity: dirt146,
    transform: dirt146transform,
    GLTFShape: dirt244GLTFShape,
  },
  dirt5:{
    entity: dirt547,
    transform: dirt547transform,
    GLTFShape: dirt244GLTFShape,
  },
  dirt6:{
    entity: dirt648,
    transform: dirt648transform,
    GLTFShape: dirt244GLTFShape,
  },
  dirt4:{
    entity: dirt449,
    transform: dirt449transform,
    GLTFShape: dirt244GLTFShape,
  },
  well:{
    entity: well55,
    transform: well55transform,
    GLTFShape: well55GLTFShape,
  },
  pond:{
    entity: pond74,
    transform: pond74transform,
    GLTFShape: pond74GLTFShape,
  },
  wellBucket2:{
    entity: wellBucket277,
    transform: wellBucket277transform,
    GLTFShape: wellBucket277GLTFShape,
  },
  wellBucket3:{
    entity: wellBucket378,
    transform: wellBucket378transform,
    GLTFShape: wellBucket277GLTFShape,
  },
  wellBucket1:{
    entity: wellBucket179,
    transform: wellBucket179transform,
    GLTFShape: wellBucket277GLTFShape,
  },
  signGarden:{
    entity: signGarden111,
    transform: signGarden111transform,
    GLTFShape: signGarden111GLTFShape,
  },
  couch:{
    entity: couch126,
    transform: couch126transform,
    GLTFShape: couch126GLTFShape,
  },
  bed:{
    entity: bed136,
    transform: bed136transform,
    GLTFShape: bed136GLTFShape,
  },
  chest:{
    entity: chest138,
    transform: chest138transform,
    GLTFShape: chest138GLTFShape,
  },
  door:{
    entity: door154,
    transform: door154transform,
    GLTFShape: door154GLTFShape,
  },
  gem1:{
    entity: gem1180,
    transform: gem1180transform,
    GLTFShape: gem1180GLTFShape,
  },
  gem3:{
    entity: gem3181,
    transform: gem3181transform,
    GLTFShape: gem1180GLTFShape,
  },
  gem5:{
    entity: gem5184,
    transform: gem5184transform,
    GLTFShape: gem1180GLTFShape,
  },
  gem4:{
    entity: gem4185,
    transform: gem4185transform,
    GLTFShape: gem1180GLTFShape,
  },
  gem2:{
    entity: gem2200,
    transform: gem2200transform,
    GLTFShape: gem1180GLTFShape,
  },
  candle:{
    entity: candle207,
    transform: candle207transform,
    GLTFShape: hwn20Candle02191GLTFShape,
  },
}

