// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass017 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass017)
const floorBaseGrass017transform = new Transform({
  position: new Vector3(24, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass017.addComponentOrReplace(floorBaseGrass017transform)
const floorBaseGrass017GLTFShape = new GLTFShape("models/grass/FloorBaseGrass_01.glb")
floorBaseGrass017GLTFShape.withCollisions = true
floorBaseGrass017GLTFShape.isPointerBlocker = true
floorBaseGrass017GLTFShape.visible = true
floorBaseGrass017.addComponentOrReplace(floorBaseGrass017GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass018 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass018)
const floorBaseGrass018transform = new Transform({
  position: new Vector3(8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass018.addComponentOrReplace(floorBaseGrass018transform)
floorBaseGrass018.addComponentOrReplace(floorBaseGrass017GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0110 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0110)
const floorBaseGrass0110transform = new Transform({
  position: new Vector3(8, 0, 24),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0110.addComponentOrReplace(floorBaseGrass0110transform)
floorBaseGrass0110.addComponentOrReplace(floorBaseGrass017GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorBaseGrass0111 = new Entity("Floor Base Grass 01")
engine.addEntity(floorBaseGrass0111)
const floorBaseGrass0111transform = new Transform({
  position: new Vector3(24, 0, 24),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorBaseGrass0111.addComponentOrReplace(floorBaseGrass0111transform)
floorBaseGrass0111.addComponentOrReplace(floorBaseGrass017GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0212 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0212)
const stoneSlabSmall0212transform = new Transform({
  position: new Vector3(19, 0, 0),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0212.addComponentOrReplace(stoneSlabSmall0212transform)
const stoneSlabSmall0212GLTFShape = new GLTFShape("models/stoneSlab/StoneSlabSmall_02/StoneSlabSmall_02.glb")
stoneSlabSmall0212GLTFShape.withCollisions = true
stoneSlabSmall0212GLTFShape.isPointerBlocker = true
stoneSlabSmall0212GLTFShape.visible = true
stoneSlabSmall0212.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const house6MBrown14 = new Entity("House 6 M Brown")
engine.addEntity(house6MBrown14)
const house6MBrown14transform = new Transform({
  position: new Vector3(22.25, 0, 7.25),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
house6MBrown14.addComponentOrReplace(house6MBrown14transform)
const house6MBrown14GLTFShape = new GLTFShape("models/house/House 6 M Brown.glb")
house6MBrown14GLTFShape.withCollisions = true
house6MBrown14GLTFShape.isPointerBlocker = true
house6MBrown14GLTFShape.visible = true
house6MBrown14.addComponentOrReplace(house6MBrown14GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0215 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0215)
const stoneSlabSmall0215transform = new Transform({
  position: new Vector3(19, 0, 7.5),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0215.addComponentOrReplace(stoneSlabSmall0215transform)
stoneSlabSmall0215.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0216 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0216)
const stoneSlabSmall0216transform = new Transform({
  position: new Vector3(19, 0, 2.5),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0216.addComponentOrReplace(stoneSlabSmall0216transform)
stoneSlabSmall0216.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0217 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0217)
const stoneSlabSmall0217transform = new Transform({
  position: new Vector3(19, 0, 5),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0217.addComponentOrReplace(stoneSlabSmall0217transform)
stoneSlabSmall0217.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0218 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0218)
const stoneSlabSmall0218transform = new Transform({
  position: new Vector3(19, 0, 10),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0218.addComponentOrReplace(stoneSlabSmall0218transform)
stoneSlabSmall0218.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0219 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0219)
const stoneSlabSmall0219transform = new Transform({
  position: new Vector3(19, 0, 12.5),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0219.addComponentOrReplace(stoneSlabSmall0219transform)
stoneSlabSmall0219.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0220 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0220)
const stoneSlabSmall0220transform = new Transform({
  position: new Vector3(22, 0, 4.5),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0220.addComponentOrReplace(stoneSlabSmall0220transform)
stoneSlabSmall0220.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0223 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0223)
const stoneSlabSmall0223transform = new Transform({
  position: new Vector3(16, 0, 5.5),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0223.addComponentOrReplace(stoneSlabSmall0223transform)
stoneSlabSmall0223.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0125 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0125)
const fenceWoodMedium0125transform = new Transform({
  position: new Vector3(12.75, 0, 0.75),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0125.addComponentOrReplace(fenceWoodMedium0125transform)
const fenceWoodMedium0125GLTFShape = new GLTFShape("models/fence/FenceWoodMedium_01.glb")
fenceWoodMedium0125GLTFShape.withCollisions = true
fenceWoodMedium0125GLTFShape.isPointerBlocker = true
fenceWoodMedium0125GLTFShape.visible = true
fenceWoodMedium0125.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0126 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0126)
const fenceWoodMedium0126transform = new Transform({
  position: new Vector3(9.75, 0, 0.75),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0126.addComponentOrReplace(fenceWoodMedium0126transform)
fenceWoodMedium0126.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0127 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0127)
const fenceWoodMedium0127transform = new Transform({
  position: new Vector3(6.75, 0, 0.75),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0127.addComponentOrReplace(fenceWoodMedium0127transform)
fenceWoodMedium0127.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0128 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0128)
const fenceWoodMedium0128transform = new Transform({
  position: new Vector3(3.75, 0, 0.75),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0128.addComponentOrReplace(fenceWoodMedium0128transform)
fenceWoodMedium0128.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0129 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0129)
const fenceWoodMedium0129transform = new Transform({
  position: new Vector3(0.75, 0, 0.75),
  rotation: new Quaternion(0, 1, 0, -7.450581E-08),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0129.addComponentOrReplace(fenceWoodMedium0129transform)
fenceWoodMedium0129.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0130 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0130)
const fenceWoodMedium0130transform = new Transform({
  position: new Vector3(0.75, 0, 3.75),
  rotation: new Quaternion(0, 1, 0, -7.450581E-08),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0130.addComponentOrReplace(fenceWoodMedium0130transform)
fenceWoodMedium0130.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0131 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0131)
const fenceWoodMedium0131transform = new Transform({
  position: new Vector3(0.75, 0, 6.75),
  rotation: new Quaternion(0, 1, 0, -7.450581E-08),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0131.addComponentOrReplace(fenceWoodMedium0131transform)
fenceWoodMedium0131.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0132 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0132)
const fenceWoodMedium0132transform = new Transform({
  position: new Vector3(0.75, 0, 9.75),
  rotation: new Quaternion(0, 1, 0, -7.450581E-08),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0132.addComponentOrReplace(fenceWoodMedium0132transform)
fenceWoodMedium0132.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0133 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0133)
const fenceWoodMedium0133transform = new Transform({
  position: new Vector3(0.75, 0, 12.75),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0133.addComponentOrReplace(fenceWoodMedium0133transform)
fenceWoodMedium0133.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0134 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0134)
const fenceWoodMedium0134transform = new Transform({
  position: new Vector3(3.75, 0, 12.75),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0134.addComponentOrReplace(fenceWoodMedium0134transform)
fenceWoodMedium0134.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0135 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0135)
const fenceWoodMedium0135transform = new Transform({
  position: new Vector3(6.75, 0, 12.75),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0135.addComponentOrReplace(fenceWoodMedium0135transform)
fenceWoodMedium0135.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0136 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0136)
const fenceWoodMedium0136transform = new Transform({
  position: new Vector3(9.75, 0, 12.75),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0136.addComponentOrReplace(fenceWoodMedium0136transform)
fenceWoodMedium0136.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0137 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0137)
const fenceWoodMedium0137transform = new Transform({
  position: new Vector3(12.75, 0, 12.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0137.addComponentOrReplace(fenceWoodMedium0137transform)
fenceWoodMedium0137.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodMedium0138 = new Entity("Fence Wood Medium 01")
engine.addEntity(fenceWoodMedium0138)
const fenceWoodMedium0138transform = new Transform({
  position: new Vector3(12.75, 0, 3.75),
  rotation: new Quaternion(0, 4.470348E-08, 0, 1),
  scale: new Vector3(1, 1, 1)
})
fenceWoodMedium0138.addComponentOrReplace(fenceWoodMedium0138transform)
fenceWoodMedium0138.addComponentOrReplace(fenceWoodMedium0125GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const fenceWoodEnd0139 = new Entity("Fence Wood End 01")
engine.addEntity(fenceWoodEnd0139)
const fenceWoodEnd0139transform = new Transform({
  position: new Vector3(12.75, 0, 9.75),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
fenceWoodEnd0139.addComponentOrReplace(fenceWoodEnd0139transform)
const fenceWoodEnd0139GLTFShape = new GLTFShape("models/fenceWoodEnd/FenceWoodEnd_01/FenceWoodEnd_01.glb")
fenceWoodEnd0139GLTFShape.withCollisions = true
fenceWoodEnd0139GLTFShape.isPointerBlocker = true
fenceWoodEnd0139GLTFShape.visible = true
fenceWoodEnd0139.addComponentOrReplace(fenceWoodEnd0139GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeSycamore0340 = new Entity("Tree Sycamore 03")
engine.addEntity(treeSycamore0340)
const treeSycamore0340transform = new Transform({
  position: new Vector3(2.75, 0, 2.25),
  rotation: new Quaternion(0, 0.9914449, 0, 0.1305263),
  scale: new Vector3(1, 0.75, 1)
})
treeSycamore0340.addComponentOrReplace(treeSycamore0340transform)
const treeSycamore0340GLTFShape = new GLTFShape("models/treeSycamore/TreeSycamore_03/TreeSycamore_03.glb")
treeSycamore0340GLTFShape.withCollisions = true
treeSycamore0340GLTFShape.isPointerBlocker = true
treeSycamore0340GLTFShape.visible = true
treeSycamore0340.addComponentOrReplace(treeSycamore0340GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const store0241 = new Entity("Store 02")
engine.addEntity(store0241)
const store0241transform = new Transform({
  position: new Vector3(9, 0, 10),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1, 1, 1)
})
store0241.addComponentOrReplace(store0241transform)
const store0241GLTFShape = new GLTFShape("models/store/Store_02.glb")
store0241GLTFShape.withCollisions = true
store0241GLTFShape.isPointerBlocker = true
store0241GLTFShape.visible = true
store0241.addComponentOrReplace(store0241GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const cartBigClosed42 = new Entity("Cart Big Closed")
engine.addEntity(cartBigClosed42)
const cartBigClosed42transform = new Transform({
  position: new Vector3(4.5, 0, 9.75),
  rotation: new Quaternion(0, 0.5000001, 0, 0.8660254),
  scale: new Vector3(1, 1, 1)
})
cartBigClosed42.addComponentOrReplace(cartBigClosed42transform)
const cartBigClosed42GLTFShape = new GLTFShape("models/cartBig/Cart Big Closed.glb")
cartBigClosed42GLTFShape.withCollisions = true
cartBigClosed42GLTFShape.isPointerBlocker = true
cartBigClosed42GLTFShape.visible = true
cartBigClosed42.addComponentOrReplace(cartBigClosed42GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeSycamore0343 = new Entity("Tree Sycamore 03")
engine.addEntity(treeSycamore0343)
const treeSycamore0343transform = new Transform({
  position: new Vector3(2.25, 0, 12),
  rotation: new Quaternion(0, 0.7933534, 0, -0.6087615),
  scale: new Vector3(1, 1, 1)
})
treeSycamore0343.addComponentOrReplace(treeSycamore0343transform)
treeSycamore0343.addComponentOrReplace(treeSycamore0340GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const dirt0444 = new Entity("Dirt 04")
engine.addEntity(dirt0444)
const dirt0444transform = new Transform({
  position: new Vector3(11.25, 0, 2.25),
  rotation: new Quaternion(0, 0.9238796, 0, -0.3826834),
  scale: new Vector3(1, 1, 1)
})
dirt0444.addComponentOrReplace(dirt0444transform)
const dirt0444GLTFShape = new GLTFShape("models/dirt/Dirt_04.glb")
dirt0444GLTFShape.withCollisions = true
dirt0444GLTFShape.isPointerBlocker = true
dirt0444GLTFShape.visible = true
dirt0444.addComponentOrReplace(dirt0444GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const dirt0445 = new Entity("Dirt 04")
engine.addEntity(dirt0445)
const dirt0445transform = new Transform({
  position: new Vector3(8, 0, 3.75),
  rotation: new Quaternion(0, 0.6087615, 0, -0.7933534),
  scale: new Vector3(1, 1, 1)
})
dirt0445.addComponentOrReplace(dirt0445transform)
dirt0445.addComponentOrReplace(dirt0444GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const dirt0446 = new Entity("Dirt 04")
engine.addEntity(dirt0446)
const dirt0446transform = new Transform({
  position: new Vector3(10, 0, 6.25),
  rotation: new Quaternion(0, 0.258819, 0, 0.9659259),
  scale: new Vector3(1, 1, 1)
})
dirt0446.addComponentOrReplace(dirt0446transform)
dirt0446.addComponentOrReplace(dirt0444GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const dirt0447 = new Entity("Dirt 04")
engine.addEntity(dirt0447)
const dirt0447transform = new Transform({
  position: new Vector3(4.25, 0, 6.25),
  rotation: new Quaternion(0, 0.5000001, 0, -0.8660254),
  scale: new Vector3(1, 1, 1)
})
dirt0447.addComponentOrReplace(dirt0447transform)
dirt0447.addComponentOrReplace(dirt0444GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const dirt0448 = new Entity("Dirt 04")
engine.addEntity(dirt0448)
const dirt0448transform = new Transform({
  position: new Vector3(2, 0, 4.25),
  rotation: new Quaternion(0, 0.7933534, 0, -0.6087615),
  scale: new Vector3(1, 1, 1)
})
dirt0448.addComponentOrReplace(dirt0448transform)
dirt0448.addComponentOrReplace(dirt0444GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const dirt0449 = new Entity("Dirt 04")
engine.addEntity(dirt0449)
const dirt0449transform = new Transform({
  position: new Vector3(5, 0, 2.25),
  rotation: new Quaternion(0, 0.9659259, 0, -0.258819),
  scale: new Vector3(1, 1, 1)
})
dirt0449.addComponentOrReplace(dirt0449transform)
dirt0449.addComponentOrReplace(dirt0444GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeFir0250 = new Entity("Tree Fir 02")
engine.addEntity(treeFir0250)
const treeFir0250transform = new Transform({
  position: new Vector3(20.25, 0, 1.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.75, 0.5, 0.75)
})
treeFir0250.addComponentOrReplace(treeFir0250transform)
const treeFir0250GLTFShape = new GLTFShape("models/treeFir/TreeFir_02.glb")
treeFir0250GLTFShape.withCollisions = true
treeFir0250GLTFShape.isPointerBlocker = true
treeFir0250GLTFShape.visible = true
treeFir0250.addComponentOrReplace(treeFir0250GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeSycamore0351 = new Entity("Tree Sycamore 03")
engine.addEntity(treeSycamore0351)
const treeSycamore0351transform = new Transform({
  position: new Vector3(20.25, 0, 8.25),
  rotation: new Quaternion(0, 0.9914449, 0, 0.1305263),
  scale: new Vector3(1, 1, 1)
})
treeSycamore0351.addComponentOrReplace(treeSycamore0351transform)
treeSycamore0351.addComponentOrReplace(treeSycamore0340GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stoneSlabSmall0252 = new Entity("Stone Slab Small 02")
engine.addEntity(stoneSlabSmall0252)
const stoneSlabSmall0252transform = new Transform({
  position: new Vector3(22, 0, 10),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(2.5, 1, 3)
})
stoneSlabSmall0252.addComponentOrReplace(stoneSlabSmall0252transform)
stoneSlabSmall0252.addComponentOrReplace(stoneSlabSmall0212GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const treeSycamore0354 = new Entity("Tree Sycamore 03")
engine.addEntity(treeSycamore0354)
const treeSycamore0354transform = new Transform({
  position: new Vector3(14, 0, 10.5),
  rotation: new Quaternion(0, 1, 0, -2.533197E-07),
  scale: new Vector3(0.75, 0.75, 0.75)
})
treeSycamore0354.addComponentOrReplace(treeSycamore0354transform)
treeSycamore0354.addComponentOrReplace(treeSycamore0340GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const well0155 = new Entity("Well 01")
engine.addEntity(well0155)
const well0155transform = new Transform({
  position: new Vector3(23.5, 0, 11.25),
  rotation: new Quaternion(0, 0.3826835, 0, 0.9238795),
  scale: new Vector3(1.75, 1.25, 1.75)
})
well0155.addComponentOrReplace(well0155transform)
const well0155GLTFShape = new GLTFShape("models/well/Well_01.glb")
well0155GLTFShape.withCollisions = true
well0155GLTFShape.isPointerBlocker = true
well0155GLTFShape.visible = true
well0155.addComponentOrReplace(well0155GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const logs256 = new Entity("Logs 2")
engine.addEntity(logs256)
const logs256transform = new Transform({
  position: new Vector3(28.75, 0, 9),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2.75, 2.75, 2.75)
})
logs256.addComponentOrReplace(logs256transform)
const logs256GLTFShape = new GLTFShape("models/logPile/Logs 2.glb")
logs256GLTFShape.withCollisions = true
logs256GLTFShape.isPointerBlocker = true
logs256GLTFShape.visible = true
logs256.addComponentOrReplace(logs256GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const axe257 = new Entity("Axe 2")
engine.addEntity(axe257)
const axe257transform = new Transform({
  position: new Vector3(28.75, 0, 11.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
axe257.addComponentOrReplace(axe257transform)
const axe257GLTFShape = new GLTFShape("models/axe/Axe 2.glb")
axe257GLTFShape.withCollisions = true
axe257GLTFShape.isPointerBlocker = true
axe257GLTFShape.visible = true
axe257.addComponentOrReplace(axe257GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const outdoorBoxLamp59 = new Entity("Outdoor Box Lamp")
engine.addEntity(outdoorBoxLamp59)
const outdoorBoxLamp59transform = new Transform({
  position: new Vector3(22.25, 2, 6.75),
  rotation: new Quaternion(0, 0.7071069, 0, -0.7071068),
  scale: new Vector3(0.75, 0.75, 0.75)
})
outdoorBoxLamp59.addComponentOrReplace(outdoorBoxLamp59transform)
const outdoorBoxLamp59GLTFShape = new GLTFShape("models/outdoorLamp/Outdoor Box Lamp.glb")
outdoorBoxLamp59GLTFShape.withCollisions = true
outdoorBoxLamp59GLTFShape.isPointerBlocker = true
outdoorBoxLamp59GLTFShape.visible = true
outdoorBoxLamp59.addComponentOrReplace(outdoorBoxLamp59GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const window2x2V2Closed60 = new Entity("Window 2x2 V2 Closed")
engine.addEntity(window2x2V2Closed60)
const window2x2V2Closed60transform = new Transform({
  position: new Vector3(22.25, 4, 6.25),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071069),
  scale: new Vector3(1, 1, 1)
})
window2x2V2Closed60.addComponentOrReplace(window2x2V2Closed60transform)
const window2x2V2Closed60GLTFShape = new GLTFShape("models/windowClosed/Window 2x2 V2 Closed.glb")
window2x2V2Closed60GLTFShape.withCollisions = true
window2x2V2Closed60GLTFShape.isPointerBlocker = true
window2x2V2Closed60GLTFShape.visible = true
window2x2V2Closed60.addComponentOrReplace(window2x2V2Closed60GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const window2x2V2Closed61 = new Entity("Window 2x2 V2 Closed")
engine.addEntity(window2x2V2Closed61)
const window2x2V2Closed61transform = new Transform({
  position: new Vector3(22.25, 4, 3.25),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071069),
  scale: new Vector3(1, 1, 1)
})
window2x2V2Closed61.addComponentOrReplace(window2x2V2Closed61transform)
window2x2V2Closed61.addComponentOrReplace(window2x2V2Closed60GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const window2x2V2Closed62 = new Entity("Window 2x2 V2 Closed")
engine.addEntity(window2x2V2Closed62)
const window2x2V2Closed62transform = new Transform({
  position: new Vector3(31.25, 4, 5.25),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
window2x2V2Closed62.addComponentOrReplace(window2x2V2Closed62transform)
window2x2V2Closed62.addComponentOrReplace(window2x2V2Closed60GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const window2x2V2Closed63 = new Entity("Window 2x2 V2 Closed")
engine.addEntity(window2x2V2Closed63)
const window2x2V2Closed63transform = new Transform({
  position: new Vector3(31.25, 4, 2.25),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1, 1, 1)
})
window2x2V2Closed63.addComponentOrReplace(window2x2V2Closed63transform)
window2x2V2Closed63.addComponentOrReplace(window2x2V2Closed60GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const shovel64 = new Entity("Shovel")
engine.addEntity(shovel64)
const shovel64transform = new Transform({
  position: new Vector3(7.75, 0, 1.5),
  rotation: new Quaternion(-0.2981333, -0.1244852, -0.03925003, 0.9455578),
  scale: new Vector3(1.25, 1, 1)
})
shovel64.addComponentOrReplace(shovel64transform)
const shovel64GLTFShape = new GLTFShape("models/shovel/Shovel.glb")
shovel64GLTFShape.withCollisions = true
shovel64GLTFShape.isPointerBlocker = true
shovel64GLTFShape.visible = true
shovel64.addComponentOrReplace(shovel64GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const window2x2V2Closed65 = new Entity("Window 2x2 V2 Closed")
engine.addEntity(window2x2V2Closed65)
const window2x2V2Closed65transform = new Transform({
  position: new Vector3(23.2, 3, 1.25),
  rotation: new Quaternion(0, 1, 0, -7.450581E-08),
  scale: new Vector3(1, 1.3, 1)
})
window2x2V2Closed65.addComponentOrReplace(window2x2V2Closed65transform)
window2x2V2Closed65.addComponentOrReplace(window2x2V2Closed60GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const flower0166 = new Entity("Flower 01")
engine.addEntity(flower0166)
const flower0166transform = new Transform({
  position: new Vector3(9.45, 1.3, 10.6),
  rotation: new Quaternion(-0.258819, 0, 0, 0.9659259),
  scale: new Vector3(0.75, 0.75, 0.75)
})
flower0166.addComponentOrReplace(flower0166transform)
const flower0166GLTFShape = new GLTFShape("models/sunflower/Flower_01.glb")
flower0166GLTFShape.withCollisions = true
flower0166GLTFShape.isPointerBlocker = true
flower0166GLTFShape.visible = true
flower0166.addComponentOrReplace(flower0166GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const flower0167 = new Entity("Flower 01")
engine.addEntity(flower0167)
const flower0167transform = new Transform({
  position: new Vector3(11.3, 1.3, 10.6),
  rotation: new Quaternion(-0.258819, 0, 0, 0.9659259),
  scale: new Vector3(0.75, 0.75, 0.75)
})
flower0167.addComponentOrReplace(flower0167transform)
flower0167.addComponentOrReplace(flower0166GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const window2x2V4OpenV168 = new Entity("Window 2x2 V4 Open v1")
engine.addEntity(window2x2V4OpenV168)
const window2x2V4OpenV168transform = new Transform({
  position: new Vector3(22.25, 0.5, 4.25),
  rotation: new Quaternion(0, 0.7071068, 0, -0.7071068),
  scale: new Vector3(1.9, 1.1, 1)
})
window2x2V4OpenV168.addComponentOrReplace(window2x2V4OpenV168transform)
const window2x2V4OpenV168GLTFShape = new GLTFShape("models/windowOpen/Window 2x2 V4 Open v1.glb")
window2x2V4OpenV168GLTFShape.withCollisions = true
window2x2V4OpenV168GLTFShape.isPointerBlocker = true
window2x2V4OpenV168GLTFShape.visible = true
window2x2V4OpenV168.addComponentOrReplace(window2x2V4OpenV168GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
}

